services:
  - type: web
    name: scriptly
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: SECRET_KEY
        generateValue: true
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: FB_API_KEY
        sync: false
      - key: FB_AUTH_DOMAIN
        sync: false
      - key: FB_PROJECT_ID
        sync: false
      - key: FB_STORAGE_BUCKET
        sync: false
      - key: FB_SENDER_ID
        sync: false
      - key: FB_APP_ID
        sync: false
      - key: FB_MEASUREMENT_ID
        sync: false
      - key: RAPIDAPI_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
